# Generated by Django 2.0.5 on 2018-05-10 17:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugtickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('bug_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bugtickets.BugTicket')),
            ],
        ),
        migrations.AlterField(
            model_name='bugupvote',
            name='bug_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_votes', to='bugtickets.BugTicket'),
        ),
    ]
