# Generated by Django 2.0.5 on 2018-05-22 12:57

import bugtickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugticket',
            name='bug_type',
            field=models.CharField(choices=[('functional', 'Functional'), ('communication', 'Communication'), ('command error', 'Something Missing'), ('syntactic error', 'Spelling & Grammar'), ('error handling errors', 'Error Notices'), ('calculation bugs', 'Bad Calculations'), ('control flow', 'Not Doing What it Should!'), ('other', 'Unsure')], default=bugtickets.models.default_bug_type, max_length=30),
        ),
    ]
