# Generated by Django 2.0.5 on 2018-05-24 03:05

import bugtickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtickets', '0002_bugticket_bug_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugticket',
            name='bug_type',
            field=models.CharField(choices=[('Functional', 'functional'), ('Communication', 'communication'), ('Something Missing', 'command error'), ('Spelling & Grammar', 'syntactic error'), ('Error Notices', 'error handling errors'), ('Bad Calculations', 'calculation bugs'), ('Not Doing What it Should!', 'control flow'), ('Unsure', 'other')], default=bugtickets.models.default_bug_type, max_length=30),
        ),
        migrations.AlterField(
            model_name='bugticket',
            name='status',
            field=models.CharField(choices=[('Pending', 'todo'), ('In Progress', 'doing'), ('Complete', 'done')], default=bugtickets.models.default_status, max_length=20),
        ),
    ]
