# Generated by Django 2.0.5 on 2018-05-24 04:32

import bugtickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtickets', '0003_auto_20180524_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugticket',
            name='bug_type',
            field=models.CharField(choices=[('Functional', 'Functional'), ('Communication', 'Communication'), ('Something Missing', 'Something Missing'), ('Spelling & Grammar', 'Spelling & Grammar'), ('Error Notices', 'Error Notices'), ('Bad Calculations', 'Bad Calculations'), ('Not Doing What it Should!', 'Not Doing What it Should!'), ('Unsure', 'Unsure')], default=bugtickets.models.default_bug_type, max_length=30),
        ),
        migrations.AlterField(
            model_name='bugticket',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Complete', 'Complete')], default=bugtickets.models.default_status, max_length=20),
        ),
    ]
