# Generated by Django 2.0.5 on 2018-05-29 01:33

import bugtickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtickets', '0004_auto_20180524_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugticket',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bugticket',
            name='date_started',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bugticket',
            name='status',
            field=models.CharField(choices=[('checking', 'checking'), ('doing', 'doing'), ('complete', 'complete')], default=bugtickets.models.default_status, max_length=20),
        ),
    ]
