# Generated by Django 2.0.5 on 2018-05-08 12:07

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import featuretickets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('links', models.URLField(blank=True)),
                ('contribution', models.FloatField(validators=[django.core.validators.MinValueValidator(9.99), django.core.validators.MaxValueValidator(999.99)])),
                ('status', models.CharField(choices=[('todo', 'Pending'), ('doing', 'In Progress'), ('done', 'Complete')], default=featuretickets.models.default_status, max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
