# Generated by Django 2.0.5 on 2018-05-12 21:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import featuretickets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('links', models.URLField(blank=True)),
                ('contribution', models.DecimalField(decimal_places=2, default=9.99, max_digits=8)),
                ('total_contributions', models.DecimalField(decimal_places=2, default=9.99, max_digits=8)),
                ('status', models.CharField(choices=[('todo', 'Pending'), ('doing', 'In Progress'), ('done', 'Complete')], default=featuretickets.models.default_status, max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureUpvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('vote_type', models.CharField(max_length=10)),
                ('feature_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_votes', to='featuretickets.FeatureTicket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='feature_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_comments', to='featuretickets.FeatureTicket'),
        ),
        migrations.AlterUniqueTogether(
            name='featureupvote',
            unique_together={('feature_ticket', 'user', 'vote_type')},
        ),
    ]
