# Generated by Django 2.0.5 on 2018-05-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featuretickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureticket',
            name='contribution',
            field=models.DecimalField(decimal_places=2, default=10.0, editable=False, max_digits=8),
        ),
    ]
