# Generated by Django 2.0.5 on 2018-05-12 02:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('featuretickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to=settings.AUTH_USER_MODEL)),
                ('feature_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_comments', to='featuretickets.FeatureTicket')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureUpvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('vote_type', models.CharField(max_length=10)),
                ('feature_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_votes', to='featuretickets.FeatureTicket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='featureupvote',
            unique_together={('feature_ticket', 'user', 'vote_type')},
        ),
    ]
