# Generated by Django 2.0.5 on 2018-06-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featuretickets', '0002_auto_20180530_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureticket',
            name='report',
            field=models.TextField(null=True),
        ),
    ]
