# Generated by Django 2.0.5 on 2018-05-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featuretickets', '0005_auto_20180514_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureticket',
            name='contribution',
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=8),
        ),
    ]
