# Generated by Django 2.0.5 on 2018-05-14 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('featuretickets', '0006_auto_20180514_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureticket',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='featureupvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_user_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
