# Generated by Django 2.0.5 on 2018-05-21 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('featuretickets', '0007_auto_20180514_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureticket',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_features', to=settings.AUTH_USER_MODEL),
        ),
    ]
