# Generated by Django 2.0.5 on 2018-05-24 03:06

from django.db import migrations, models
import featuretickets.models


class Migration(migrations.Migration):

    dependencies = [
        ('featuretickets', '0008_auto_20180521_0346'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='featureupvote',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='featureupvote',
            name='feature_ticket',
        ),
        migrations.RemoveField(
            model_name='featureupvote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='featureticket',
            name='total_contributions',
        ),
        migrations.AlterField(
            model_name='featureticket',
            name='contribution',
            field=models.DecimalField(decimal_places=2, default=9.99, editable=False, max_digits=8),
        ),
        migrations.AlterField(
            model_name='featureticket',
            name='status',
            field=models.CharField(choices=[('Pending', 'todo'), ('In Progress', 'doing'), ('Complete', 'done')], default=featuretickets.models.default_status, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='FeatureUpvote',
        ),
    ]
