# Generated by Django 2.0.5 on 2018-05-24 04:33

from django.db import migrations, models
import featuretickets.models


class Migration(migrations.Migration):

    dependencies = [
        ('featuretickets', '0009_auto_20180524_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureticket',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Complete', 'Complete')], default=featuretickets.models.default_status, max_length=20, null=True),
        ),
    ]
