# Generated by Django 2.0.5 on 2018-05-10 01:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugtickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugUpvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('vote_type', models.CharField(max_length=10)),
                ('bug_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs_votes', to='bugtickets.BugTicket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='bugupvote',
            unique_together={('bug_ticket', 'user', 'date_created', 'vote_type')},
        ),
    ]
