# Generated by Django 2.0.5 on 2018-06-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(default='No profile description provided.', null=True),
        ),
    ]
