# Generated by Django 2.0.5 on 2018-06-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180531_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alert',
            field=models.TextField(blank=True, null=True),
        ),
    ]
