# Generated by Django 2.0.5 on 2018-06-05 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_alert_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='alert',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='alert_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='trade_union',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
