# Generated by Django 2.0.5 on 2018-06-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180605_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='alert_date',
            field=models.DateField(default='', null=True),
        ),
    ]
