# Generated by Django 2.0.5 on 2018-06-06 00:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180605_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='alert_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
