# Generated by Django 2.0.5 on 2018-05-14 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='county_state',
            new_name='county',
        ),
    ]
