# Generated by Django 2.0.5 on 2018-05-24 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20180515_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features_vote', to='featuretickets.FeatureTicket'),
        ),
    ]
