# Generated by Django 2.0.5 on 2018-05-07 18:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tickets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_profile_trade_union'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('ticket', models.CharField(choices=[('bug', 'Problem'), ('feature', 'Proposal')], max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('status', models.CharField(default=tickets.models.default_status, max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
    ]
