# Generated by Django 2.0.5 on 2018-05-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_tickets_contribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='contribution',
            field=models.DecimalField(blank=True, decimal_places=2, default=9.99, max_digits=6),
        ),
    ]
